package agents

import (
	"backend/main/llama"
	"backend/models"
	"fmt"

	"os"
)

type FrontendAgent struct {
	llamaClient *llama.Client
}

func NewFrontendAgent() *FrontendAgent {
	return &FrontendAgent{
		llamaClient: llama.NewClient("http://localhost:8080"),
	}
}

func (f *FrontendAgent) Generate(config *models.ProjectConfig) error {
	if err := f.generatePage(config); err != nil {
		return err
	}
	if err := f.generateLayout(config); err != nil {
		return err
	}
	if err := f.generateTodoComponent(config); err != nil {
		return err
	}
	if err := f.generateAPIService(config); err != nil {
		return err
	}
	if err := f.generatePackageJSON(config); err != nil {
		return err
	}
	if err := f.generateGlobalStyles(config); err != nil {
		return err
	}
	return nil
}

func (f *FrontendAgent) generatePage(config *models.ProjectConfig) error {
	content := `'use client';

import { useState, useEffect } from 'react';
import { TodoList } from '@/components/TodoList';
import { api } from '@/services/api';
import { Container, Title, AddButton } from './styles';

export default function Home() {
  const [todos, setTodos] = useState([]);

  useEffect(() => {
    fetchTodos();
  }, []);

  const fetchTodos = async () => {
    const data = await api.getTodos();
    setTodos(data);
  };

  return (
    <Container>
      <Title>Todo List</Title>
      <TodoList todos={todos} onUpdate={fetchTodos} />
      <AddButton onClick={() => {/* Implementar */}}>
        + Add Todo
      </AddButton>
    </Container>
  );
}`
	return os.WriteFile(config.FrontendPath+"/app/page.tsx", []byte(content), 0644)
}

func (f *FrontendAgent) generateLayout(config *models.ProjectConfig) error {
	content := `import type { Metadata } from 'next';
import { StyledComponentsRegistry } from '@/lib/registry';

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by MCP Orchestrator',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}`

	registryContent := `'use client';

import React, { useState } from 'react';
import { useServerInsertedHTML } from 'next/navigation';
import { ServerStyleSheet, StyleSheetManager } from 'styled-components';

export default function StyledComponentsRegistry({
  children,
}: {
  children: React.ReactNode;
}) {
  const [styledComponentsStyleSheet] = useState(() => new ServerStyleSheet());

  useServerInsertedHTML(() => {
    const styles = styledComponentsStyleSheet.getStyleElement();
    styledComponentsStyleSheet.instance.clearTag();
    return <>{styles}</>;
  });

  if (typeof window !== 'undefined') return <>{children}</>;

  return (
    <StyleSheetManager sheet={styledComponentsStyleSheet.instance}>
      {children}
    </StyleSheetManager>
  );
}`

	os.MkdirAll(config.FrontendPath+"/lib", 0755)
	os.WriteFile(config.FrontendPath+"/lib/registry.tsx", []byte(registryContent), 0644)
	return os.WriteFile(config.FrontendPath+"/app/layout.tsx", []byte(content), 0644)
}

func (f *FrontendAgent) generateTodoComponent(config *models.ProjectConfig) error {
	componentContent := `'use client';

import { TodoItem } from './TodoItem';
import { ListContainer } from './styles';

interface Todo {
  id: string;
  title: string;
  completed: boolean;
}

interface TodoListProps {
  todos: Todo[];
  onUpdate: () => void;
}

export function TodoList({ todos, onUpdate }: TodoListProps) {
  return (
    <ListContainer>
      {todos.map((todo) => (
        <TodoItem key={todo.id} todo={todo} onUpdate={onUpdate} />
      ))}
    </ListContainer>
  );
}`

	stylesContent := "import styled from 'styled-components';\n\n" +
		"export const ListContainer = styled.div" + "`" + `\n` +
		`  display: flex;\n` +
		`  flex-direction: column;\n` +
		`  gap: 1rem;\n` +
		`  padding: 1rem;\n` +
		"`" + `;\n\n` +
		"export const ItemContainer = styled.div<{ completed: boolean }>" + "`" + `\n` +
		`  display: flex;\n` +
		`  align-items: center;\n` +
		`  gap: 1rem;\n` +
		`  padding: 1rem;\n` +
		`  background: white;\n` +
		`  border-radius: 8px;\n` +
		`  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\n` +
		`  text-decoration: ${props => props.completed ? 'line-through' : 'none'};\n` +
		`  opacity: ${props => props.completed ? 0.7 : 1};\n` +
		"`" + `;\n\n` +
		"export const Title = styled.span" + "`" + `\n` +
		`  flex: 1;\n` +
		`  font-size: 1rem;\n` +
		"`" + `;\n\n` +
		"export const Checkbox = styled.input" + "`" + `\n` +
		`  width: 20px;\n` +
		`  height: 20px;\n` +
		`  cursor: pointer;\n` +
		"`" + `;\n\n` +
		"export const DeleteButton = styled.button" + "`" + `\n` +
		`  background: #ff4444;\n` +
		`  color: white;\n` +
		`  border: none;\n` +
		`  padding: 0.5rem 1rem;\n` +
		`  border-radius: 4px;\n` +
		`  cursor: pointer;\n` +
		`  \n` +
		`  &:hover {\n` +
		`    background: #cc0000;\n` +
		`  }\n` +
		"`" + `;`

	itemContent := `'use client';

import { ItemContainer, Title, Checkbox, DeleteButton } from './styles';

interface Todo {
  id: string;
  title: string;
  completed: boolean;
}

interface TodoItemProps {
  todo: Todo;
  onUpdate: () => void;
}

export function TodoItem({ todo, onUpdate }: TodoItemProps) {
  const handleToggle = async () => {
    await fetch('http://localhost:8080/api/todos/' + todo.id, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ...todo, completed: !todo.completed }),
    });
    onUpdate();
  };

  const handleDelete = async () => {
    await fetch('http://localhost:8080/api/todos/' + todo.id, {
      method: 'DELETE',
    });
    onUpdate();
  };

  return (
    <ItemContainer completed={todo.completed}>
      <Checkbox
        type="checkbox"
        checked={todo.completed}
        onChange={handleToggle}
      />
      <Title>{todo.title}</Title>
      <DeleteButton onClick={handleDelete}>Delete</DeleteButton>
    </ItemContainer>
  );
}`

	os.MkdirAll(config.FrontendPath+"/components/TodoList", 0755)
	os.WriteFile(config.FrontendPath+"/components/TodoList/index.tsx", []byte(componentContent), 0644)
	os.WriteFile(config.FrontendPath+"/components/TodoList/styles.ts", []byte(stylesContent), 0644)
	os.WriteFile(config.FrontendPath+"/components/TodoList/TodoItem.tsx", []byte(itemContent), 0644)

	return nil
}

func (f *FrontendAgent) generateAPIService(config *models.ProjectConfig) error {
	content := fmt.Sprintf(`const API_BASE_URL = 'http://localhost:%s';

export const api = {
  async getTodos() {
    const response = await fetch(API_BASE_URL + '/api/todos');
    return response.json();
  },
  
  async createTodo(todo: any) {
    const response = await fetch(API_BASE_URL + '/api/todos', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(todo),
    });
    return response.json();
  },
  
  async updateTodo(id: string, todo: any) {
    const response = await fetch(API_BASE_URL + '/api/todos/' + id, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(todo),
    });
    return response.json();
  },
  
  async deleteTodo(id: string) {
    await fetch(API_BASE_URL + '/api/todos/' + id, {
      method: 'DELETE',
    });
  },
};`, config.BackendPort)

	return os.WriteFile(config.FrontendPath+"/services/api.ts", []byte(content), 0644)
}

func (f *FrontendAgent) generatePackageJSON(config *models.ProjectConfig) error {
	content := `{
  "name": "todo-frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.0.4",
    "react": "^18",
    "react-dom": "^18",
    "styled-components": "^6.1.8"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@types/styled-components": "^5.1.34",
    "typescript": "^5"
  }
}`

	return os.WriteFile(config.FrontendPath+"/package.json", []byte(content), 0644)
}

func (f *FrontendAgent) generateGlobalStyles(config *models.ProjectConfig) error {
	content := "import { createGlobalStyle } from 'styled-components';\n\n" +
		"export const GlobalStyle = createGlobalStyle" + "`" + `\n` +
		`  * {\n` +
		`    margin: 0;\n` +
		`    padding: 0;\n` +
		`    box-sizing: border-box;\n` +
		`  }\n` +
		`  \n` +
		`  body {\n` +
		`    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;\n` +
		`    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n` +
		`    min-height: 100vh;\n` +
		`  }\n` +
		`  \n` +
		`  button {\n` +
		`    cursor: pointer;\n` +
		`    transition: all 0.3s ease;\n` +
		`  }\n` +
		"`" + `;\n`

	return os.WriteFile(config.FrontendPath+"/styles/global.ts", []byte(content), 0644)
}
